version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - .:/server
    ports:
      - "8000:8000"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - .:/client
    depends_on:
      - server
