FROM python:3.10

WORKDIR /server

COPY ./requirements/server.txt /server/

RUN pip install -r server.txt

COPY ./server.py /server/

EXPOSE 8000

CMD ["uvicorn", "server:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
